rhboot/pesign

libdpe/Makefile
when building packages (e.g. for openSUSE Linux)
(random) filesystem order of input files
influences ordering of functions in the output,
thus without the patch, builds (in disposable VMs) would differ.
See https://reproducible-builds.org/ for why this matters.
=> sort input files

src/siglist.c
signature_list wasn't copied corretly to efi_signature_list because
SignatureType in signature_list is a pointer while that in
efi_signature_list is not.
Signed-off-by: Gary Lin <glin@suse.com>
=> efisiglist: Copy the header correctly

src/efikeygen.1
So says the source, but neither was mentioned in the man page.
Signed-off-by: Adam Jackson <ajax@redhat.com>
=> efikeygen: either --kernel or --module must be used

src/pesign.service.in
This will simplify troubleshooting pesign as by default messages will now be sent to the journal rather than nowhere.
=> Send pesign stdout/err to systemd journal

Make.defaults
This will automatically set the correct include and lib paths for required pesign libraries.
=> Add default packages for pkg-config

src/pesign-authorize
On my system pesign-authorize ends up running before the socket is created.  I've added a slight delay and rearranged the directory scan.  This provides sufficient delay on my system.
=> Short delay to ensure /run/pesign/socket exists

src/actions.c
Noticed this when I was removing signatures on a file that was going to be distributed for one of the products. pesign will crash due to memory corruption if this memmove is executed.
Here are some examples of the pointers before and after fixing the issue:
Without the change:
```
$ pesign -r -u 0 -i EFI/BOOT/bootx64.efi -o EFI/BOOT/bootx64.efi.new
before: sig[0]=0x5582aa9ba790 sig[0]->data=0x5582aa9ba7b0
before: sig[1]=0x5582aa9bad20 sig[1]->data=0x5582aa9bad40
before: sig[2]=0x5582aa9bb430 sig[2]->data=0x5582aa9bb450
after : sig[0]=0x5582aa9ba790 sig[0]->data=0x5582aa9bad40
after : sig[1]=0x5582aa9bad20 sig[1]->data=0x5582aa9bad40
malloc(): invalid next size (unsorted)
[1]    1014756 abort (core dumped)  ~/Downloads/pesign/src/pesign -r -u 0 -i EFI/BOOT/bootx64.efi1 -o 
```
```
$ pesign …
```
=> Resolve crash when signature that is removed is not the end of the list

src/client.c, src/daemon.c
When version mismatch is detected, print both versions in hexadecimal
format which is also the format used in PESIGND_VERSION macro definition.
This change helps to identify versions used on both sides in case of
mismatch.
Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>
=> Enhance error diagnostics about version mismatch

.github/workflows/pr.yml, Make.defaults, libdpe/pe_updatefile.c, src/compiler.h, src/daemon.c, src/password.c, src/util.h
The compile_assert() fix probably isn't quite right; suggestions welcome.
=> Fix build on gcc 12 and non-Fedora

src/macros.pesign, src/pesign-rpmbuild-helper.in
Effectively reverts 30b488682a92c524bb9c0d450c34e9abc0b56de9
Also, make our argument parser fail on extra arguments to make it easier
to debug when this kind of thing happens again.
Signed-off-by: Robbie Harwood <rharwood@redhat.com>
=> macros: drop %{_pesign_args}

src/pesign-rpmbuild-helper.in
Signed-off-by: Peter Jones <pjones@redhat.com>
[rharwood: manually reapply to main]
Signed-off-by: Robbie Harwood <rharwood@redhat.com>
=> Detect the presence of rpm-sign when checking for "rhel"-ness

src/certdb.c
Set selected_digest when the digest is found in db or dbx.
This fixes a crash in get_digest().
Signed-off-by: Visa Hankala <visa@hankala.org>
=> pesigcheck: Fix crash on digest match

src/certdb.c, src/cms_common.c, src/cms_common.h, src/content_info.c, src/file_kmod.c, src/file_pe.c, src/pesigcheck.c
Storage as an index is problematic because the sentinel value -1 was
used, but accesses were unchecked, leading to crashes like that in
3b1031a6b779cb80c11b34eec84c5a0cc215efed ("pesigcheck: Fix crash on
digest match").  By storing a pointer, we get an explicit NULL
dereference: still a crash, but preferred since it's clearer.
Since the index was previously also used for retrieving digest
parameters, include a pointer to the relevant struct digest_param in the
struct digest.
Signed-off-by: Robbie Harwood <rharwood@redhat.com>
[This is the refactor suggested in #90.]
=> cms: store digest as pointer instead of index

Make.rules
Bizarrely, mandoc doesn't default to outputting man - the default is
"locale", which is either ASCII or UTF-8 (by locale).  This output is
supposed to be some kind of plain-text, but it's formatted so strangely
I'm not sure what the purpose is.  Regardless, it doesn't go well to
feed this into man(1).
Tell mandoc explicitly to produce man pages.
Signed-off-by: Robbie Harwood <rharwood@redhat.com>
[It's not clear to me why we're using mandoc at all.  The mdoc files appear to be valid man pages already.]
=> Fix mandoc invocation to not produce garbage

src/daemon.c, src/password.c
This fixes two problems I've had related to reading PINs while diagnosing https://bugzilla.redhat.com/show_bug.cgi?id=2122777 .
=> Password fixes

src/certs/make-certs
In make-certs, the codes of lines 33-36 is duplicate with the codes of lines 37-40, so delete the duplicate codes.
Fixes: #96
Signed-off-by: YiLin.Li <YiLin.Li@linux.alibaba.com>
=> src/certs/make-certs: delete the duplicate codes

src/cms_common.c
In find_certificate_by_callback, function return -1 directly without free resource if node is null, that will lead to nss shut down failed.
The error message as below:
could not shut down NSS: NSS could not shutdown. Objects are still in use.
To fix this issue, free all resources before function return -1.
Signed-off-by: Chenxi Mao <chenxi.mao@suse.com>
=> Free resources if certification cannot be found

src/cms_common.c
In find_certificate_by_callback(), the match() returns 1 when cert subject is matched.
Signed-off-by: Huaxin Lu <luhuaxin1@huawei.com>
=> cms_common: fix cert match check

src/cms_common.c
When finding a certificate in a 'Friendly' slot without the need of the private key, it is not necessary to authenticate the slot.
Signed-off-by: Gary Lin <glin@suse.com>
=> cms_common: skip authentication on the 'Friendly' slot

src/cms_common.c
When running efikeygen, the binary crashes with a segfault due to dereferencing a **ptr instead of a *ptr.
=> cms_common: Fixed Segmentation fault

src/pesign.1.mdoc
The following changes have been introduced:
- Documented how to read password from file/environment variable
- Documented how to make use of /etc/pki/pesign as regular user
- Added the --pinfile/--pwfile options to synopsis
- Bumped Mdocdate
- Added and example on OpenDNSSEC's SoftHSM usage
- Fixed a typo: cryptorgaphic -> cryptographic
- Added myself to the document authors list
=> Various pesign.1.mdoc fixes and improvements

src/daemon.c
Previously ctx.pid was getting it's value indirectly from fork(), which is always zero in the child process.
Fixed a bug introduced in 2b3ca2b.
=> daemon: fix pid value by using getpid() in the child process

Make.defaults, src/Makefile
`ENABLE_DOCS=0` make will remove the man page files from the list of targets to build and install. This is useful if the target OS does not ship manpages and so the builder doesn't have `mandoc`.
=> make: add option to disable building/installing the docs

src/pesigcheck.c
The prototype is "void *calloc(size_t nelem, size_t elsize);"
These two instances had them reversed, almost certainly leading to buffer overflow issues. This was detected by
-Werror=calloc-transposed-args on gcc.
Fixes #117
=> Fix reversed calloc() arguments

src/file_pe.c, src/wincert.c
=> pesign: Fix signature removal

Make.defaults
Signed-off-by; Steve McIntyre <93sam@debian.org>
=> Make.defaults: disable arm32 warnings about wchar_t

src/cms_common.c, src/efikeygen.c, src/pesign.c
Fixes: github issue #105
Fixes: 12f1671 (Rework the wildly undocumented NSS password file goo.)
Complements: 1a4481e (Add more ways to use a password with the token)
=> Initialize pwdata in efikeygen and pesign
